version: "3"
services:
  app:
    build: .
    # COMMAND TO RUN THE APPLICATION
    command: python -u app.py
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    # INITIALISING THE DATABASE WITH PROVIDED DETAILS
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
